#pragma once
#include <windows.h>
#include <windowsx.h>
#include <commctrl.h>
#include <shlobj.h>
#include <tchar.h>
#include <wincodec.h>
#include <magnification.h>
#include <Uxtheme.h>
#include <math.h>
#include <shellapi.h>
#include <shlwapi.h>
#include <stdio.h>
#include <memory>
#include <new>
#include "registry.h"
#include "resource.h"
#include "dll.h"
#define GDIPVER 0x0110
#include <gdiplus.h>
#include <vector>
#include <string>
#include <list>
#include <atomic>
#include <memory>
#include <algorithm>
#include <filesystem>
#include <future>
#include <regex>
#include <fstream>
#include <sstream>
#include <utility>
#include "NativeResources.h"
#include "SelectRectangle.h"
#include "VersionHelper.h"

#include "Hardening.h"
#include <deque>
